export const VEIL_VAULT_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_paymentToken", type: "address", internalType: "address" },
      { name: "_defaultQueryFee", type: "uint256", internalType: "uint256" },
      { name: "_platformFeeBps", type: "uint256", internalType: "uint256" },
      { name: "_queryExpiry", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "storeCredential",
    inputs: [
      {
        name: "credType",
        type: "uint8",
        internalType: "enum VeilVault.CredentialType",
      },
      { name: "commitment", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeCredential",
    inputs: [
      {
        name: "credType",
        type: "uint8",
        internalType: "enum VeilVault.CredentialType",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setQueryFee",
    inputs: [{ name: "fee", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitQuery",
    inputs: [
      { name: "dataOwner", type: "address", internalType: "address" },
      {
        name: "credType",
        type: "uint8",
        internalType: "enum VeilVault.CredentialType",
      },
      { name: "queryHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "answerQuery",
    inputs: [
      { name: "queryId", type: "uint256", internalType: "uint256" },
      { name: "answer", type: "bool", internalType: "bool" },
      { name: "proof", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "expireQuery",
    inputs: [{ name: "queryId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawRevenue",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawPlatformRevenue",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registerAgent",
    inputs: [{ name: "agent", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getQueryFee",
    inputs: [{ name: "dataOwner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCredential",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      {
        name: "credType",
        type: "uint8",
        internalType: "enum VeilVault.CredentialType",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct VeilVault.Credential",
        components: [
          { name: "commitment", type: "bytes32", internalType: "bytes32" },
          {
            name: "credType",
            type: "uint8",
            internalType: "enum VeilVault.CredentialType",
          },
          { name: "timestamp", type: "uint256", internalType: "uint256" },
          { name: "active", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getQuery",
    inputs: [{ name: "queryId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct VeilVault.QueryRequest",
        components: [
          { name: "requester", type: "address", internalType: "address" },
          { name: "dataOwner", type: "address", internalType: "address" },
          {
            name: "credType",
            type: "uint8",
            internalType: "enum VeilVault.CredentialType",
          },
          { name: "queryHash", type: "bytes32", internalType: "bytes32" },
          { name: "payment", type: "uint256", internalType: "uint256" },
          {
            name: "status",
            type: "uint8",
            internalType: "enum VeilVault.QueryStatus",
          },
          { name: "answer", type: "bool", internalType: "bool" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "answeredAt", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEarnings",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [
      { name: "pending", type: "uint256", internalType: "uint256" },
      { name: "total", type: "uint256", internalType: "uint256" },
      { name: "totalQueries", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setDefaultQueryFee",
    inputs: [{ name: "fee", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPlatformFeeBps",
    inputs: [{ name: "bps", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setQueryExpiry",
    inputs: [{ name: "expiry", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "credentials",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint8", internalType: "enum VeilVault.CredentialType" },
    ],
    outputs: [
      { name: "commitment", type: "bytes32", internalType: "bytes32" },
      {
        name: "credType",
        type: "uint8",
        internalType: "enum VeilVault.CredentialType",
      },
      { name: "timestamp", type: "uint256", internalType: "uint256" },
      { name: "active", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "queries",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "requester", type: "address", internalType: "address" },
      { name: "dataOwner", type: "address", internalType: "address" },
      {
        name: "credType",
        type: "uint8",
        internalType: "enum VeilVault.CredentialType",
      },
      { name: "queryHash", type: "bytes32", internalType: "bytes32" },
      { name: "payment", type: "uint256", internalType: "uint256" },
      {
        name: "status",
        type: "uint8",
        internalType: "enum VeilVault.QueryStatus",
      },
      { name: "answer", type: "bool", internalType: "bool" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "answeredAt", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextQueryId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingRevenue",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalEarned",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "queryCount",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "defaultQueryFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userAgents",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "queryExpiry",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CredentialStored",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "credType",
        type: "uint8",
        indexed: true,
        internalType: "enum VeilVault.CredentialType",
      },
      {
        name: "commitment",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "event",
    name: "CredentialRevoked",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "credType",
        type: "uint8",
        indexed: true,
        internalType: "enum VeilVault.CredentialType",
      },
    ],
  },
  {
    type: "event",
    name: "QueryCreated",
    inputs: [
      {
        name: "queryId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "requester",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "dataOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "credType",
        type: "uint8",
        indexed: false,
        internalType: "enum VeilVault.CredentialType",
      },
      {
        name: "payment",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },
  {
    type: "event",
    name: "QueryAnswered",
    inputs: [
      {
        name: "queryId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "answer",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
  },
  {
    type: "event",
    name: "QueryExpired",
    inputs: [
      {
        name: "queryId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
  },
  {
    type: "event",
    name: "RevenueWithdrawn",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },
  {
    type: "event",
    name: "AgentRegistered",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "agent",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
  },
  {
    type: "event",
    name: "QueryFeeUpdated",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },
] as const;
